language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t vjy0574/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true vjy0574/react-test npm test
after_success:
    - docker build -t vjy0574/multi-client ./client
    - docker build -t vjy0574/multi-nginx ./nginx
    - docker build -t vjy0574/multi-server ./server
    - docker build -t vjy0574/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin docker.io
    # Take those images and psuh them to docker hub
    - docker push vjy0574/multi-client
    - docker push vjy0574/multi-nginx
    - docker push vjy0574/multi-server
    - docker push vjy0574/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "multi-docker-react"
    env: "MultiDockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-619365515374"
    bucket_path: "multi-docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY