language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t vjy0574/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true vjy0574/react-test npm test
after_success:
    - docker build -t vjy0574/multi-client ./client
    - docker build -t vjy0574/multi-nginx ./nginx
    - docker build -t vjy0574/multi-server ./server
    - docker build -t vjy0574/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin docker.io
    # Take those images and psuh them to docker hub
    - docker psuh vjy0574/multi-client
    - docker psuh vjy0574/multi-nginx
    - docker psuh vjy0574/multi-server
    - docker psuh vjy0574/multi-worker